from . import (
    AnimeFade,
    Anime,
    Banner,
    Calligraphy,
    Cascade,
    ComicBook,
    Cutout,
    Divider,
    Fade,
    FormulaOne,
    Frame,
    Graph,
    Inset,
    Landscape,
    Logo,
    Marvel,
    Music,
    NegativeSpace,
    Notification,
    Olivier,
    Overline,
    Poster,
    RomanNumeral,
    Score,
    Shape,
    SkeletonCrew,
    Standard,
    StarWars,
    Striped,
    Textless,
    TintedFrame,
    TintedGlass,
    WhiteBorder,
)
from app.cards.base import BaseCardType

BUILTIN_CARD_TYPES: dict[str, type[BaseCardType]] = {
    '4x3': Fade.FadeTitleCard,
    'anime': Anime.AnimeTitleCard,
    'anime fade': AnimeFade.AnimeFadeTitleCard,
    'banner': Banner.BannerTitleCard,
    'blurred border': TintedFrame.TintedFrameTitleCard,
    'calligraphy': Calligraphy.CalligraphyTitleCard,
    'cascade': Cascade.CascadeTitleCard,
    'comic book': ComicBook.ComicBookTitleCard,
    'cutout': Cutout.CutoutTitleCard,
    'divider': Divider.DividerTitleCard,
    'f1': FormulaOne.FormulaOneTitleCard,
    'fade': Fade.FadeTitleCard,
    'fade anime': AnimeFade.AnimeFadeTitleCard,
    'formula 1': FormulaOne.FormulaOneTitleCard,
    'frame': Frame.FrameTitleCard,
    'generic': Standard.StandardTitleCard,
    'graph': Graph.GraphTitleCard,
    'gundam': Poster.PosterTitleCard,
    'import': Textless.TextlessTitleCard,
    'inset': Inset.InsetTitleCard,
    'ishalioh': Olivier.OlivierTitleCard,
    'landscape': Landscape.LandscapeTitleCard,
    'logo': Logo.LogoTitleCard,
    'marvel': Marvel.MarvelTitleCard,
    'music': Music.MusicTitleCard,
    'musikmann': WhiteBorder.WhiteBorderTitleCard,
    'negative': NegativeSpace.NegativeSpaceTitleCard,
    'negative space': NegativeSpace.NegativeSpaceTitleCard,
    'notification': Notification.NotificationTitleCard,
    'olivier': Olivier.OlivierTitleCard,
    'overline': Overline.OverlineTitleCard,
    'phendrena': Cutout.CutoutTitleCard,
    'photo': Frame.FrameTitleCard,
    'polygon': Striped.StripedTitleCard,
    'polymath': Standard.StandardTitleCard,
    'poster': Poster.PosterTitleCard,
    'reality tv': Logo.LogoTitleCard,
    'roman': RomanNumeral.RomanNumeralTitleCard,
    'roman numeral': RomanNumeral.RomanNumeralTitleCard,
    'score': Score.ScoreTitleCard,
    'shape': Shape.ShapeTitleCard,
    'sherlock': TintedGlass.TintedGlassTitleCard,
    'skeleton crew': SkeletonCrew.SkeletonCrewTitleCard,
    'spotify': Music.MusicTitleCard,
    'standard': Standard.StandardTitleCard,
    'star wars': StarWars.StarWarsTitleCard,
    'striped': Striped.StripedTitleCard,
    'textless': Textless.TextlessTitleCard,
    'tinted frame': TintedFrame.TintedFrameTitleCard,
    'tinted glass': TintedGlass.TintedGlassTitleCard,
    'white border': WhiteBorder.WhiteBorderTitleCard,
}

__all__ = [
    'AnimeFade',
    'Anime',
    'Banner',
    'Calligraphy',
    'Cascade',
    'ComicBook',
    'Cutout',
    'Divider',
    'Fade',
    'FormulaOne',
    'Frame',
    'Graph',
    'Inset',
    'Landscape',
    'Logo',
    'Marvel',
    'Music',
    'NegativeSpace',
    'Notification',
    'Olivier',
    'Overline',
    'Poster',
    'RomanNumeral',
    'Score',
    'Shape',
    'SkeletonCrew',
    'Standard',
    'StarWars',
    'Striped',
    'Textless',
    'TintedFrame',
    'TintedGlass',
    'WhiteBorder',
]
