describe('Logs Page', () => {
  beforeEach(() => {
    // Reset database to ensure clean state
    cy.resetDatabase();

    // Visit the logs page
    cy.visit('/logs');
    
    // Wait for the page to load and initialize
    cy.get('#log-filters').should('be.visible');
    cy.get('#log-table').should('be.visible');
    cy.wait(500); // Allow time for initial data loading
  });

  describe('Page Structure and Loading', () => {
    it('Loads the logs page with all expected elements', () => {
      // Verify page title
      cy.get('.settings-panel-header').first().should('contain', 'System Logs');

      // Verify filter form exists
      cy.get('#log-filters').scrollIntoView().should('be.visible');

      // Verify log table exists
      cy.get('#log-table').should('be.visible');
      cy.get('#log-table thead tr').should('contain', 'Level');
      cy.get('#log-table thead tr').should('contain', 'Timestamp');
      cy.get('#log-table thead tr').should('contain', 'Context ID');
      cy.get('#log-table thead tr').should('contain', 'Message');

      // Verify internal server errors section exists
      cy.get('.settings-panel').last().should('contain', 'Internal Server Errors');
    });

    it('Displays filter form with all expected fields', () => {
      // Message contains field
      cy.get('input[name="contains"]').should('be.visible');
      cy.get('label').contains('Message Contains').should('be.visible');

      // Context ID field
      cy.get('input[name="context_id"]').should('be.visible');
      cy.get('label').contains('Context IDs').should('be.visible');

      // Start date field
      cy.get('#date-after input[name="after"]').should('be.visible');
      cy.get('label').contains('Start Date').should('be.visible');

      // End date field
      cy.get('#date-before input[name="before"]').should('be.visible');
      cy.get('label').contains('End Date').should('be.visible');

      // Log level dropdown
      cy.get('.dropdown[data-value="level"]').should('be.visible');
      cy.get('label').contains('Minimum Level').should('be.visible');

      // Page size dropdown
      cy.get('.dropdown[data-value="size"]').should('be.visible');
      cy.get('label').contains('Page Size').should('be.visible');
    });

    it('Has working action buttons', () => {
      // Refresh logs button
      cy.get('[data-action="refresh"]').first().should('be.visible');
      cy.get('[data-action="refresh"]').first().should('contain', 'Refresh');

      // Reset filters button
      cy.get('[data-action="refresh"]').last().should('contain', 'Reset');
    });

    it('Loads initial log data', () => {
      // Verify that log data is loaded (either has rows or shows empty state)
      cy.get('#log-data').should('exist');

      // Check if pagination exists (indicating data was loaded)
      cy.get('#pagination').should('exist');
    });

    it('Shows internal server errors section', () => {
      // Verify the section exists
      cy.get('.settings-panel').last().should('contain', 'Internal Server Errors');
    });
  });

  describe('Filter Functionality', () => {
    it('Filters logs by message content', () => {
      // This is generated by the reset database function
      const searchText = 'Deleting SQL Table';

      // Enter text in the contains field
      cy.get('input[name="contains"]').type(searchText);

      // Click refresh logs button
      cy.get('[data-action="refresh"]').first().click();

      // Verify the filter was applied (this will depend on whether test data exists)
      cy.get('input[name="contains"]').should('have.value', searchText);
    });

    it('Filters logs by context ID', () => {
      const contextId = 'test123';
      
      // Enter context ID in the field
      cy.get('input[name="context_id"]').type(contextId);
      
      // Click refresh logs button
      cy.get('[data-action="refresh"]').first().click();
      
      // Verify the filter was applied
      cy.get('input[name="context_id"]').should('have.value', contextId);
    });

    it('Filters logs by date range', () => {
      // Set start date
      cy.get('#date-after input[name="after"]').type('2024-01-01T00:00:00');
      
      // Set end date
      cy.get('#date-before input[name="before"]').type('2024-12-31T23:59:59');
      
      // Click refresh logs button
      cy.get('[data-action="refresh"]').first().click();
      
      // Verify the dates were set
      cy.get('#date-after input[name="after"]').should('have.value', '2024-01-01T00:00:00');
      cy.get('#date-before input[name="before"]').should('have.value', '2024-12-31T23:59:59');
    });

    it('Changes log level filter', () => {
      // Click on the log level dropdown
      cy.get('.dropdown[data-value="level"]').click();
      
      // Select a different level (Warning)
      cy.get('.dropdown[data-value="level"] .menu .item').contains('Warning').click();
      
      // Verify the selection was made
      cy.get('.dropdown[data-value="level"] .text').should('contain', 'Warning');
      
      // Click refresh logs button
      cy.get('[data-action="refresh"]').first().click();
    });

    it('Changes page size', () => {
      // Click on the page size dropdown
      cy.get('.dropdown[data-value="size"]').click();
      
      // Select a different size (250)
      cy.get('.dropdown[data-value="size"] .menu .item').contains('250').click();
      
      // Verify the selection was made
      cy.get('.dropdown[data-value="size"] .text').should('contain', '250');
      
      // Click refresh logs button
      cy.get('[data-action="refresh"]').first().click();
    });

    it('Resets all filters', () => {
      // Set some filter values
      cy.get('input[name="contains"]').type('test');
      cy.get('input[name="context_id"]').type('test123');
      cy.get('#date-after input[name="after"]').type('2024-01-01T00:00:00');
      
      // Click reset filters button
      cy.get('[data-action="refresh"]').last().click();
      
      // Verify all fields were cleared
      cy.get('input[name="contains"]').should('have.value', '');
      cy.get('input[name="context_id"]').should('have.value', '');
      cy.get('#date-after input[name="after"]').should('have.value', '');
    });

    it('Processes multiple context IDs correctly', () => {
      // Test with multiple comma-separated context IDs
      const multipleIds = 'abc123,def456,ghi789';
      
      cy.get('input[name="context_id"]').type(multipleIds);
      cy.get('[data-action="refresh"]').first().click();
      
      // Verify the filter was applied correctly
      cy.get('input[name="context_id"]').should('have.value', multipleIds);
    });

    it('Handles special characters in search filters', () => {
      // Test with special characters that might be in log messages
      const specialText = 'error[500] & exception: "test"';
      
      cy.get('input[name="contains"]').type(specialText);
      cy.get('[data-action="refresh"]').first().click();
      
      // Verify the filter was applied
      cy.get('input[name="contains"]').should('have.value', specialText);
    });

    it('Handles very long search queries', () => {
      // Test with a very long search query
      const longText = 'a'.repeat(1000);
      
      cy.get('input[name="contains"]').type(longText);
      cy.get('[data-action="refresh"]').first().click();
      
      // Verify the filter was applied
      cy.get('input[name="contains"]').should('have.value', longText);
    });

    it('Handles empty filter submissions', () => {
      // Submit filters with no values
      cy.get('[data-action="refresh"]').first().click();
      
      // Verify the page still functions normally
      cy.get('#log-table').should('be.visible');
      cy.get('#log-data').should('exist');
    });

    it('Maintains table structure during filtering', () => {
      // Apply a filter
      cy.get('input[name="contains"]').type('test');
      cy.get('[data-action="refresh"]').first().click();
      
      // Verify table structure is maintained
      cy.get('#log-table thead tr').should('contain', 'Level');
      cy.get('#log-table thead tr').should('contain', 'Timestamp');
      cy.get('#log-table thead tr').should('contain', 'Context ID');
      cy.get('#log-table thead tr').should('contain', 'Message');
    });
  });

  describe('Interactive Features', () => {
    it('Updates timestamp filters when clicking on timestamp cells', () => {
      // Check if any log entries exist
      cy.get('#log-data tr').then(($rows) => {
        if ($rows.length > 0) {
          // Click on the first timestamp cell
          cy.wrap($rows.first()).within(() => {
            cy.get('[data-value="timestamp"]').click();
          });
          
          // Verify the timestamp filter was updated
          // This should populate either the start or end date field
          cy.get('#date-after input[name="after"], #date-before input[name="before"]').should('not.have.value', '');
        }
      });
    });

    it('Updates context ID filter when clicking on context ID cells', () => {
      // Check if any log entries exist with context IDs
      cy.get('#log-data tr').then(($rows) => {
        if ($rows.length > 0) {
          // Find a row with a context ID
          const $rowWithContextId = $rows.filter((i, el) => {
            const contextId = Cypress.$(el).find('[data-value="context_id"]').text().trim();
            return contextId !== '';
          }).first();
          
          if ($rowWithContextId.length > 0) {
            // Click on the context ID cell
            cy.wrap($rowWithContextId).within(() => {
              cy.get('[data-value="context_id"]').click();
            });
            
            // Verify the context ID filter was updated
            cy.get('input[name="context_id"]').should('not.have.value', '');
          }
        }
      });
    });

    it('Handles rich formatting in log messages', () => {
      // This test verifies that the rich formatting function works
      // We'll test by setting a filter that should trigger rich formatting
      cy.get('input[name="contains"]').type('Series');
      cy.get('[data-action="refresh"]').first().click();
      
      // Verify the filter was applied
      cy.get('input[name="contains"]').should('have.value', 'Series');
    });

    it('Shows tooltips on interactive elements', () => {
      // Verify tooltips exist on timestamp and context ID cells
      cy.get('[data-tooltip="Add time as Filter"]').should('exist');
      cy.get('[data-tooltip="Add ID as Filter"]').should('exist');
    });

    it('Handles calendar date picker functionality', () => {
      // Test that calendar inputs are properly initialized
      cy.get('#date-after').should('have.class', 'ui');
      cy.get('#date-after').should('have.class', 'calendar');
      cy.get('#date-before').should('have.class', 'ui');
      cy.get('#date-before').should('have.class', 'calendar');
    });
  });

  describe('Data Display and Pagination', () => {
    it('Displays log entries with correct structure', () => {
      // Check if log entries exist
      cy.get('#log-data tr').then(($rows) => {
        if ($rows.length > 0) {
          // Verify the first row has the expected structure
          cy.wrap($rows.first()).within(() => {
            cy.get('[data-value="level_name"]').should('exist');
            cy.get('[data-value="timestamp"]').should('exist');
            cy.get('[data-value="context_id"]').should('exist');
            cy.get('[data-value="message"]').should('exist');
          });
        }
      });
    });

    it('Shows pagination controls', () => {
      // Verify pagination exists
      cy.get('#pagination').should('exist');
      
      // If there are multiple pages, verify pagination controls work
      cy.get('#pagination .item').then(($items) => {
        if ($items.length > 1) {
          // Click on a page number if available
          cy.get('#pagination .item').not('.active').first().click();
          
          // Verify the page change was processed (this will depend on the API response)
          cy.get('#pagination').should('exist');
        }
      });
    });

    it('Displays log levels with correct styling', () => {
      // Check if any log entries exist
      cy.get('#log-data tr').then(($rows) => {
        if ($rows.length > 0) {
          // Verify that log level cells contain a badge span
          cy.wrap($rows.first()).within(() => {
            cy.get('[data-value="level_name"] .log-level-badge').should('exist');
          });
        }
      });
    });

    it('Shows timestamp in readable format', () => {
      // Check if any log entries exist
      cy.get('#log-data tr').then(($rows) => {
        if ($rows.length > 0) {
          // Verify timestamp cells render two-line date/time spans
          cy.wrap($rows.first()).within(() => {
            cy.get('[data-value="timestamp"]').should('exist');
            cy.get('[data-value="timestamp"] .log-ts-date').should('exist');
            cy.get('[data-value="timestamp"] .log-ts-time').should('exist');
          });
        }
      });
    });
  });

  describe('User Experience and Edge Cases', () => {
    it('Handles empty log results gracefully', () => {
      // Set a very restrictive filter that should return no results
      cy.get('input[name="contains"]').type('very_specific_text_that_should_not_exist_12345');
      
      // Click refresh logs button
      cy.get('[data-action="refresh"]').first().click();
      
      // Verify the table still exists even with no results
      cy.get('#log-table').should('be.visible');
      cy.get('#log-data').should('exist');
    });

    it('Clears filter state after page refresh', () => {
      // Set some filter values
      const searchText = 'persistent_test';
      cy.get('input[name="contains"]').type(searchText);
      
      // Refresh the page
      cy.reload();
      
      // Wait for page to load
      cy.get('#log-filters').should('be.visible');
      
      // Filter fields are reset on fresh page load
      cy.get('input[name="contains"]').should('have.value', '');
    });

    it('Shows loading state during API calls', () => {
      // Set a filter and click refresh
      cy.get('input[name="contains"]').type('loading_test');
      cy.get('[data-action="refresh"]').first().click();
      
      // The loading state should be handled by the JavaScript
      // We can verify the request was made by checking if the filter value persists
      cy.get('input[name="contains"]').should('have.value', 'loading_test');
    });

    it('Handles rapid filter changes', () => {
      // Rapidly change filters
      cy.get('input[name="contains"]').type('filter1');
      cy.get('[data-action="refresh"]').first().click();
      
      cy.get('input[name="contains"]').clear().type('filter2');
      cy.get('[data-action="refresh"]').first().click();
      
      cy.get('input[name="contains"]').clear().type('filter3');
      cy.get('[data-action="refresh"]').first().click();
      
      // Verify the final filter was applied
      cy.get('input[name="contains"]').should('have.value', 'filter3');
    });

    it('Validates form field accessibility', () => {
      // Check that all form fields have proper labels and are accessible
      cy.get('input[name="contains"]').should('have.attr', 'placeholder');
      cy.get('input[name="context_id"]').should('have.attr', 'placeholder');
      cy.get('#date-after input[name="after"]').should('have.attr', 'placeholder');
      cy.get('#date-before input[name="before"]').should('have.attr', 'placeholder');
    });

    it('Maintains responsive design on different screen sizes', () => {
      // Test on mobile viewport
      cy.viewport(375, 667);
      cy.get('#log-filters').should('be.visible');
      cy.get('#log-table').should('be.visible');
      
      // Test on tablet viewport
      cy.viewport(768, 1024);
      cy.get('#log-filters').should('be.visible');
      cy.get('#log-table').should('be.visible');
      
      // Reset to desktop viewport
      cy.viewport(1920, 1080);
      cy.get('#log-filters').should('be.visible');
      cy.get('#log-table').should('be.visible');
    });

    it('Allows navigation via keyboard', () => {
      // Test tab navigation through form fields
      cy.get('input[name="contains"]').focus();
      cy.press(Cypress.Keyboard.Keys.TAB);
      cy.focused().should('have.attr', 'name', 'context_id');

      cy.press(Cypress.Keyboard.Keys.TAB);
      cy.focused().should('have.attr', 'name', 'after');
      
      cy.press(Cypress.Keyboard.Keys.TAB);
      cy.focused().should('have.attr', 'name', 'before');
    });

    it('Preserves user preferences across sessions', () => {
      // Set a page size preference
      cy.get('.dropdown[data-value="size"]').click();
      cy.get('.dropdown[data-value="size"] .menu .item').contains('500').click();
      
      // Verify the selection was made
      cy.get('.dropdown[data-value="size"] .text').should('contain', '500');
      
      // The preference should persist (this depends on the implementation)
      // For now, we'll just verify the selection was made
    });

    it('Shows appropriate error messages for API failures', () => {
      // This test would require mocking API failures
      // For now, we'll test that the page handles errors gracefully
      cy.get('#log-table').should('be.visible');
      cy.get('#log-data').should('exist');
    });
  });
});
